apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sanity
  namespace: default
spec:
  schedule: "0 0 * * 0" #Once a week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sanity-wrap
            image: quay.io/ypery/ocpsanity:v1.3
            imagePullPolicy: Always
            env:
            - name: KUBECONFIG
              value: "/root/kubeconfig"
            - name:  K8S_AUTH_KUBECONFIG
              value: "/root/kubeconfig"
            command: ["/usr/bin/ansible-playbook"]
            args: ["-i", "/root/ocpstest/inventories/inventory", "/root/playbooks/perf.yaml", "-v"]
            volumeMounts:
            - name: inventory
              mountPath: /root/ocpstest/inventories/inventory
              subPath: inventory
            - name: kubeconfig
              mountPath: /root/kubeconfig
              subPath: kubeconfig
          volumes:
            - name: inventory
              configMap:
                name: inventory
              defaultMode: 0777
            - name: kubeconfig
              configMap:
                name: kubeconfig
              defaultMode: 0777
          restartPolicy: OnFailure
