apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-block-claim
  namespace: sanitytest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
          storage: 1Gi
  storageClassName: rook-ceph-block
